config/routes.rb
Rails.application.routes.draw do
  resources :flights, only: :index
  resources :bookings, only: %i[create new show] do
    get 'search', on: :collection
  end

  root 'flights#index'
end

app/models/airport.rb
# == Schema Information
#
# Table name: airports
#
#  id         :bigint           not null, primary key
#  code       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Airport < ApplicationRecord
  has_many :inbound_flights, class_name: :Flight, inverse_of: :to_airport
  has_many :outbound_flights, class_name: :Flight, inverse_of: :from_airport
  validates :code, presence: true, 
    length: { is: 3 },
    format: { with: /\A[A-Z]{3}\z/ } 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id         :bigint           not null, primary key
#  flight_id  :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Booking < ApplicationRecord
  belongs_to :flight  
  has_many :passenger_bookings
  has_many :passengers, through: :passenger_bookings, inverse_of: :bookings

  accepts_nested_attributes_for :passengers

  def self.search(query)
    return unless query

    Booking.where(confirmation_number: query)
  end

end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id              :bigint           not null, primary key
#  to_airport_id   :integer
#  from_airport_id :integer
#  start           :datetime
#  duration        :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  leaves_at       :time
#
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: :Airport, foreign_key: :from_airport_id
  belongs_to :to_airport, class_name: :Airport, foreign_key: :to_airport_id
  
  def humanize_duration
    "#{ duration / 60}h#{duration % 60}m"
  end

  def humanize_duration_long
    hours = duration / 60
    minutes = duration % 60
    "#{hours}" + " #{ 'hours'.pluralize } " + "and" + " #{minutes} " + "#{ 'minutes'.pluralize }" 
  end

end

app/models/passenger.rb
# == Schema Information
#
# Table name: passengers
#
#  id         :bigint           not null, primary key
#  name       :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Passenger < ApplicationRecord
  has_many :passenger_bookings, dependent: :delete_all
  has_many :bookings, through: :passenger_bookings, inverse_of: :passengers
  has_many :flights, through: :bookings

  validates :name, :email, presence: true
end

app/models/passenger_booking.rb
# == Schema Information
#
# Table name: passenger_bookings
#
#  id           :bigint           not null, primary key
#  passenger_id :bigint           not null
#  booking_id   :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class PassengerBooking < ApplicationRecord
  belongs_to :passenger
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  decorates_assigned :booking, :flight

  def index

  end

  def new
    @booking = Booking.new
    params[:num_passengers].to_i.times { @booking.passengers.build }
    @flight = Flight.find(params[:flight_id])
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      PassengerMailer.with(booking: @booking.id).booking_confirmation.deliver_now
      redirect_to booking_path @booking
    else
      flash.now[:alert] = ''
      flash.now.alert = @booking.errors.full_messages.join(', ')
      @flight = Flight.find(params[:booking][:flight_id])
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def search
    @result = Booking.where(confirmation_number: params[:confirmation_number])
  end


  private
  def booking_params
    params.require(:booking).permit(:flight_id, :confirmation_number, passengers_attributes: [:id, :name, :email])
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController 

  def index
    if params[:flight]
      if params[:flight][:from_airport] == params[:flight][:to_airport]
        flash.keep[:notice] = "To and from airports must be different"
        redirect_to :root
      else
        @flights = Flight.where(
          from_airport_id: params[:flight][:from_airport],
          to_airport_id: params[:flight][:to_airport],
          start: Date.strptime(params[:flight][:start], '%m/%d/%Y')).all
      end
    end
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper

  def booking_exists?
    params[:confirmation_number] && @result.any?
  end

end

app/helpers/flights_helper.rb
module FlightsHelper
  def airport_select
    Airport.all.map { |a| [a.code, a.id] }.uniq.sort
  end

  def date_select
    Flight.all.map { |d| d.start.strftime("%m/%d/%Y")}.uniq.sort
  end
end

app/views/bookings/_booking.html.erb
<div class='show-booking'>
  <h1 class='booking-header'>Booking <%= booking.confirmation_number %></h1>
  <div class='booking-details'>
    <p>Booking #<%= booking.confirmation_number %> for Flight <%= booking.flight_id %> from <%= booking.from_airport %> to <%= booking.to_airport %>
    <p>The flight departs at <%= booking.takeoff %> with an expected duration of <%= booking.duration %></p>
    <p> 
      You reserved <%= booking.total_passengers %> <%= 'seat'.pluralize(booking.total_passengers) %> for
      <% booking.passengers.each do |passenger, i = 1| %>
        <span><%= passenger.name %></span>
        <%= tag.span(' and ') if booking.total_passengers > 1 and passenger != booking.passengers.last %>
      <% end %>
    </p>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="new-booking">
  <h2>Add <%= booking.total_passengers_a == 1 ? "passenger" : "passengers'" %> name and email to book your flight</h2>
  <%= render 'flights/flight', flight: flight  %>
  <%= form_with model: booking, local: true do |form| %>
    <%= form.hidden_field :flight_id, value: @flight.id %>
    <%= form.fields_for :passengers do |passengers_form| %>
      <%= passengers_form.hidden_field :id, value: nil %>
      <h5>Passenger&nbsp;<%= passengers_form.index + 1 %></h5>
      <%= passengers_form.text_field :name, placeholder: 'Name', autofocus: true %>
      <%= passengers_form.text_field :email, placeholder: 'Email' %>
    <% end %>
    <%= form.submit 'Book flight', class: 'btn-book' %>
  <% end %>
</div>

app/views/bookings/search.html.erb
<%= form_with scope: :booking, url: search_bookings_path, method: :get do |form| %>
  <%= form.label :confirmation_number, 'Enter your confirmation number' %>
  <%= form.text_field :confirmation_number %>
  <%= form.submit :Search %>
<% end %>

<% if booking_exists? %>

  <%= @result.inspect %>
  
<% end %>

app/views/bookings/show.html.erb
<div class='show-booking'>
  <h1 class='booking-header'>Booking <%= booking.id %></h1>
  <div class='booking-details'>
    <p>You have successfully created your booking for Flight <%= booking.flight_id %> from <%= booking.from_airport %> to <%= booking.to_airport %>
    <p>The flight departs at <%= booking.takeoff %> with an expected duration of <%= booking.duration %></p>
    <p> 
      You reserved <%= booking.total_passengers %> <%= 'seat'.pluralize(booking.total_passengers) %> for
      <% booking.passengers.each do |passenger, i = 1| %>
        <span><%= passenger.name %></span>
        <%= tag.span(' and ') if booking.total_passengers > 1 and passenger != booking.passengers.last %>
      <% end %>
    </p>
  </div>
</div>

app/views/flights/_flight.html.erb
<%= content_tag :span, flight, id: "flight_#{ flight.id }" do %>
    <label style="vertical-align: middle">
      <%= flight.from_airport.code %>
      &Rightarrow;
      <%= flight.to_airport.code %>
      &#65292;
      <%= flight.leaves_at %>
      &#65292;
      <%= flight.start.strftime('%m/%d/%Y') %>
      &#65292;<%= flight.humanize_duration %>
    </label>
<% end %>

app/views/flights/_flight_results.html.erb
<div class="results">
  <% if flights %>
    <h1>We found <%= flights.count %> <%= 'flight'.pluralize(flights.count) %> for you.</h1>
    <ul>
      <% flights.each do |flight| %>
        <%= render 'flight_selection', flight: flight %>
        <%= button_to 'Add passengers',
            new_booking_path,
            method: :get,
            class: 'btn-add',
            params: { flight_id: flight.id,
                      num_passengers: params[:flight][:num_passengers] } %>  
      <% end %>
    </ul>
  <% end %>
</div>

app/views/flights/_flight_search.html.erb
<h3 class="search-header">Search for a flight</h3>
<%= form_with scope: :flight, url: flights_path, local: true, method: :get do |form| %>
  <div class="route">
    <div class="selection">
      <%= form.label :from_airport, :From %>
      <%= form.select :from_airport, airport_select, {}, class: 'select-css' %>
    </div>
    <div class="selection date">
      <%= form.label :Date %>
      <%= form.select :start, date_select, {}, class: 'select-css' %>
    </div>
  </div>
  <div class="route">
    <div class="selection">
      <%= form.label :to_airport, :To %>
      <%= form.select :to_airport, airport_select, {}, class: 'select-css' %>
    </div>
    <div class="selection passengers">
      <%= form.label :num_passengers, :Passengers %>
      <%= form.select :num_passengers, 1..4, {}, class: 'select-css' %>
    </div>
  </div>
  <div class="search">
    <%= form.submit :Search %>
  </div>
<% end %>

app/views/flights/_flight_selection.html.erb
<%= content_tag :li, flight, id: "flight_#{ flight.id }" do %>
    <label style="vertical-align: middle">
      <%= radio_button_tag :flight, flight.id %>
      <%= flight.from_airport.code %>
      &Rightarrow;
      <%= flight.to_airport.code %>
      &#65292;
      <%= flight.leaves_at.strftime('%l:%M %p') %>
      &#65292;
      <%= flight.start.strftime('%m/%d/%Y') %>
      &#65292;<%= flight.humanize_duration %>
    </label>
<% end %>

  

app/views/flights/index.html.erb
<div class='wrapper'>
  <%= render 'flight_search' %>
  <%= render 'flight_results', flights: @flights %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flight Booker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;800&display=swap" rel="stylesheet">
  </head>
  <body>
    <a href='/'>
      <header class='main-header'>          
        <h3>Flight Booker</h3>
      </header>
    </a>
    <div class='flash-messages'>
      <div class='flash-text'>
        <% flash.each do |type, message| %>
          <%= content_tag :p, message, class: type %>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>